import { IconType } from "react-icons/lib";
import {
  FaLaptop,
  FaPalette,
  FaUtensils,
  FaFilm,
  FaBook,
  FaMusic,
  FaRunning,
  FaBriefcase,
  FaTshirt,
  FaGraduationCap,
  FaFlask,
  FaTheaterMasks,
  FaHeartbeat,
  FaBuilding,
  FaCamera,
  FaChartLine,
  FaRobot,
  FaLeaf,
  FaLock,
  FaShoppingCart,
  FaGamepad,
  FaPlane,
} from "react-icons/fa";

export const categoryIcons: {
  [key: string]: { icon: IconType; color: string };
} = {
  Technology: { icon: FaLaptop, color: "#1E90FF" },
  Art: { icon: FaPalette, color: "#FFA500" },
  Food: { icon: FaUtensils, color: "#FF6347" },
  Entertainment: { icon: FaFilm, color: "#FF1493" },
  Literature: { icon: FaBook, color: "#8B4513" },
  Music: { icon: FaMusic, color: "#1DB954" },
  Sports: { icon: FaRunning, color: "#4169E1" },
  Business: { icon: FaBriefcase, color: "#708090" },
  Fashion: { icon: FaTshirt, color: "#FF69B4" },
  Education: { icon: FaGraduationCap, color: "#9370DB" },
  Science: { icon: FaFlask, color: "#00CED1" },
  Culture: { icon: FaTheaterMasks, color: "#9932CC" },
  Health: { icon: FaHeartbeat, color: "#FF0000" },
  Architecture: { icon: FaBuilding, color: "#A52A2A" },
  Photography: { icon: FaCamera, color: "#20B2AA" },
  "Digital Marketing": { icon: FaChartLine, color: "#32CD32" },
  Fintech: { icon: FaChartLine, color: "#4682B4" },
  "Artificial Intelligence": { icon: FaRobot, color: "#483D8B" },
  "Renewable Energy": { icon: FaLeaf, color: "#228B22" },
  Blockchain: { icon: FaLock, color: "#B8860B" },
  "E-Commerce": { icon: FaShoppingCart, color: "#8B008B" },
  "Mobile Game": { icon: FaGamepad, color: "#FF4500" },
  Cybersecurity: { icon: FaLock, color: "#2F4F4F" },
  "Smart City": { icon: FaBuilding, color: "#4169E1" },
  IoT: { icon: FaLaptop, color: "#9932CC" },
  "Augmented Reality": { icon: FaLaptop, color: "#8A2BE2" },
  "Drone Technology": { icon: FaPlane, color: "#2F4F4F" },
};
